### PR TITLE
Fix ndb_restor exiting with 0 despite failure

### PR DESCRIPTION
**Pull request by svenssonaxel**

### CODE REVIEW

**Review by mronstro — COMMENTED** [review]
Given that it would be good to be able to continue the restore process even in the presence of failures (like in the App cluster now), it would be good to have a flag (not default) that could be set to not set the fatal error flag.

**Comment by svenssonaxel** [comment]
Could you explain the use case? Why would we want to restore a database in an inconsistent state?

**Comment by svenssonaxel** [comment]
The use case has been explained to me. I suggest a separate PR for that.

**Comment by svenssonaxel** [comment]
RONDB-429 opened for `--force-restore`.

**Comment by svenssonaxel** [comment]
Merged as part of https://github.com/logicalclocks/rondb/pull/352

**Pull request closed without merging**
